### ISSUE TITLE
Is this project still under maintained?

### ISSUE THREAD

**Issue by Hydrogen5** [NJUPT-SAST/collection#7]
### What happened?

Is this project still under maintained?

**Comment by naivescrooge** [comment]
> 

maybe not

**Comment by matrix72c** [comment]
maybe not

**Comment by xjzsq** [comment]
Yeah, there's even an upcoming magazine called “科技星空” based on this project. Please 0xfaner explain this issue in more detail and close this issue.

**Comment by 0xfaner** [comment]
I will maintain the entire organization until next year.
